### ISSUE TITLE
when evaluation, it shows no module named 'drqa'

### ISSUE THREAD

**Issue by jiangkun1994** [jhyuklee/ParagraphRanker#1]
Below is the error output, even though I have developed the according to the [DrQA](https://github.com/facebookresearch/DrQA). I think the reason is pytorch version? Right now I am using pytorch=0.4.1, while DrQA is not compatible with this version.
Hope someone can help me thanks. 
By the way, can i do the interactive retriever with the help of Paragraph Ranker?
```
12/13/2018 05:26:03 PM: [ COMMAND: entityqa/pipeline/predict.py --query-type SQuAD --ranker-type default --reader-type default ]
12/13/2018 05:26:03 PM: [ ---------------------------------------------------------------------------------------------------- ]
12/13/2018 05:26:03 PM: [ CONFIG:
{
    "candidate_file": null,
    "cuda": true,
    "data_workers": 5,
    "db_path": "/home/jiangkunhaha/ParagraphRanker/data/wikipedia/docs.db",
    "embed_dir": "/home/jiangkunhaha/datasets",
    "embedding_dim": 300,
    "embedding_file": "/home/jiangkunhaha/datasets/glove/glove.840B.300d.txt",
    "fasttext": false,
    "gpu": -1,
    "log_file": "/home/jiangkunhaha/ParagraphRanker/entityqa/pipeline/results/20181213-d59542b8.txt",
    "match": "string",
    "model_dir": "/home/jiangkunhaha/ParagraphRanker/entityqa/pipeline/results",
    "model_name": "20181213-d59542b8",
    "module_batch_size": 64,
    "module_max_loaders": 5,
    "n_docs": 20,
    "n_pars": 200,
    "no_cuda": false,
    "parallel": false,
    "pred_file": "/home/jiangkunhaha/ParagraphRanker/entityqa/pipeline/results/pred_20181213-d59542b8.json",
    "predict_batch_size": 100,
    "query_data": "/home/jiangkunhaha/ParagraphRanker/data/datasets/SQuAD-v1.1-dev.txt",
    "query_split": "dev",
    "query_type": "SQuAD",
    "random_seed": 1013,
    "ranker_file": "/home/jiangkunhaha/ParagraphRanker/entityqa/pipeline/results/20181213-d59542b8.ranker",
    "ranker_path": "/home/jiangkunhaha/ParagraphRanker/entityqa/ranker/results/20181212-a0db0070.mdl",
    "ranker_type": "default",
    "reader_path": "/home/jiangkunhaha/ParagraphRanker/entityqa/reader/results/single.mdl",
    "reader_type": "default",
    "retriever_path": "/home/jiangkunhaha/ParagraphRanker/data/wikipedia/docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz",
    "tokenizer": "regexp",
    "train": false,
    "train_epoch": 30
} ]
12/13/2018 05:26:03 PM: [ Reading query data /home/jiangkunhaha/ParagraphRanker/data/datasets/SQuAD-v1.1-dev.txt ]
12/13/2018 05:26:03 PM: [ Initializing pipeline... ]
12/13/2018 05:26:03 PM: [ Loading retriever /home/jiangkunhaha/ParagraphRanker/data/wikipedia/docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz ]
12/13/2018 05:26:35 PM: [ Loading ranker /home/jiangkunhaha/ParagraphRanker/entityqa/ranker/results/20181212-a0db0070.mdl ]
12/13/2018 05:26:37 PM: [ Loading reader /home/jiangkunhaha/ParagraphRanker/entityqa/reader/results/single.mdl ]
Traceback (most recent call last):
  File "entityqa/pipeline/predict.py", line 367, in <module>
    main(args)
  File "entityqa/pipeline/predict.py", line 257, in main
    fixed_candidates=candidates)
  File "/home/jiangkunhaha/ParagraphRanker/entityqa/pipeline/root/pipeline/pipeline.py", line 74, in __init__
    self.reader = DocReader.load(reader_path, normalize=False)
  File "/home/jiangkunhaha/ParagraphRanker/entityqa/pipeline/root/reader/model.py", line 438, in load
    filename, map_location=lambda storage, loc: storage
  File "/home/jiangkunhaha/anaconda3/envs/ranker/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/jiangkunhaha/anaconda3/envs/ranker/lib/python3.6/site-packages/torch/serialization.py", line 542, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'drqa'

```

**Comment by jhyuklee** [comment]
I guess the drqa package was not installed properly on your environment.
I tried to remove the dependency on the drqa package (https://github.com/facebookresearch/DrQA) in the code, but it seems that somewhere it needs that package.
Try `import drqa` whether the package can be loaded properly.
We do not provide the interactive version of Paragraph Ranker, but you could easily modify the code of DrQA accordingly.

**Comment by jhyuklee** [comment]
By the way, you should also modify the pretrained models' paths in https://github.com/jhyuklee/ParagraphRanker/blob/5444963997add1ef164190342309cf8d6c9fd87d/entityqa/pipeline/predict.py#L52-L68, according to your pretrained models.

**Comment by jiangkun1994** [comment]
Thank you so much, I will have a try~

**Comment by jiangkun1994** [comment]
Sorry to bother you again, I have fixed the 'drqa' problem, it seems like it can rank paragraphs from database, but it later has an error output which is below. I didnt train the reader in your code, i download the 'simple.mdl' from [DrQA](https://github.com/facebookresearch/DrQA), is this the problem?
```
12/14/2018 08:09:45 AM: [ Reading query data /home/jiangkunhaha/ParagraphRanker/data/datasets/SQuAD-v1.1-dev.txt ]
12/14/2018 08:09:45 AM: [ Initializing pipeline... ]
12/14/2018 08:09:45 AM: [ Loading retriever /home/jiangkunhaha/ParagraphRanker/data/wikipedia/docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz ]
12/14/2018 08:10:24 AM: [ Loading ranker /home/jiangkunhaha/ParagraphRanker/entityqa/ranker/results/20181212-a0db0070.mdl ]
12/14/2018 08:10:27 AM: [ Loading reader /home/jiangkunhaha/ParagraphRanker/entityqa/reader/results/single.mdl ]
12/14/2018 08:10:29 AM: [ Initializing tokenizers... ]
12/14/2018 08:10:30 AM: [ Predicting... ]
12/14/2018 08:10:30 AM: [ ------------------------- Batch 1/106 ------------------------- ]
12/14/2018 08:10:30 AM: [ Processing 100 queries... ]
12/14/2018 08:10:30 AM: [ Retrieving top 20 docs... ]
12/14/2018 08:10:37 AM: [ Tokenizing 24614 splits ]
12/14/2018 08:10:45 AM: [ Ranking 134388 paragraphs... ]
/home/jiangkunhaha/anaconda3/envs/ranker/lib/python3.6/site-packages/torch/nn/functional.py:1006: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
12/14/2018 08:12:30 AM: [ Reading 20000 paragraphs... ]
Traceback (most recent call last):
  File "entityqa/pipeline/predict.py", line 368, in <module>
    main(args)
  File "entityqa/pipeline/predict.py", line 298, in main
    n_pars=args.n_pars)
  File "/home/jiangkunhaha/ParagraphRanker/entityqa/pipeline/root/pipeline/pipeline.py", line 365, in predict
    for batch in self._get_reader_loader(reader_examples, num_loaders): 
  File "/home/jiangkunhaha/anaconda3/envs/ranker/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/jiangkunhaha/anaconda3/envs/ranker/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):
 File "/home/jiangkunhaha/anaconda3/envs/ranker/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop    
samples = collate_fn([dataset[i] for i in batch_indices])
File "/home/jiangkunhaha/anaconda3/envs/ranker/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
  samples = collate_fn([dataset[i] for i in batch_indices])
File "/home/jiangkunhaha/ParagraphRanker/entityqa/pipeline/root/reader/data.py", line 99, in __getitem__    
return vectorize(self.examples[index], self.model, self.single_answer)
 File "/home/jiangkunhaha/ParagraphRanker/entityqa/pipeline/root/reader/vector.py", line 33, in vectorize
   q_lemma = {w for w in ex[\'qlemma\']} if args.use_lemma else None\nKeyError: \'qlemma\'\n'

```

**Comment by jiangkun1994** [comment]
by the way, the way i fixed the 'drqa' is that i copy the folder 'drqa' from [DrQA's project](https://github.com/facebookresearch/DrQA)

**Comment by jhyuklee** [comment]
For the pretraining the ranker and reader model, I suggest you to use the code provided in this repo, not the simple.mdl in DrQA. One thing I forgot is that you should preprocess the squad datasets using tokenizer=simple, not corenlp that was provided in the original DrQA. Based on the simple tokenizer based datasets, pretrain both ranker and reader models, and then evaluate the pipeline again.
And for the drqa, I think you can use setup.py which registers drqa as a python package.
